"""empty message

Revision ID: 63117d287b1d
Revises: ec6fb5ffd934
Create Date: 2025-09-24 11:11:44.801322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63117d287b1d'
down_revision = 'ec6fb5ffd934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
