"""empty message

Revision ID: d0110f127e41
Revises: 8e0f35aac45d
Create Date: 2025-09-26 10:10:35.231721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0110f127e41'
down_revision = '8e0f35aac45d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'image_path',           # 컬럼 이름
                sa.String(length=200),  # 타입
                nullable=False,         # NOT NULL
                server_default=''       # 기존 레코드 기본값 설정
            )
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
